### ISSUE TITLE
Build failure after merging https://github.com/davidgiven/fluxengine/pull/855

### ISSUE THREAD

**Issue by Sonic-Amiga** [davidgiven/fluxengine#858]
Hello everyone! Thank you for the great piece of software!
Before making a PR i did a rebase and caught build error:
```
lib/vfs/smaky6fs.cc: In member function 'std::shared_ptr<Smaky6Filesystem::SmakyDirent> Smaky6Filesystem::resolveDirent(const Path&)':
lib/vfs/smaky6fs.cc:259:53: error: no matching function for call to 'Path::Path(std::vector<std::__cxx11::basic_string<char> >::const_iterator, __gnu_cxx::__normal_iterator<const std::__cxx11::basic_string<char>*, std::vector<std::__cxx11::basic_string<char> > >)'
  259 |         Path parentPath(path.begin(), path.end() - 1);
      |                                                     ^
  • there are 5 candidates
In file included from lib/vfs/smaky6fs.cc:2:
    • candidate 1: 'Path::Path(const std::string&)'
      .obj/windows/lib/vfs/+vfs_hdr/lib/vfs/vfs.h:20:5:
         20 |     Path(const std::string& text);
            |     ^~~~
      • candidate expects 1 argument, 2 provided
    • candidate 2: 'Path::Path(std::vector<std::__cxx11::basic_string<char> >)'
      .obj/windows/lib/vfs/+vfs_hdr/lib/vfs/vfs.h:19:5:
         19 |     Path(const std::vector<std::string> other);
            |     ^~~~
      • candidate expects 1 argument, 2 provided
    • candidate 3: 'Path::Path()'
      .obj/windows/lib/vfs/+vfs_hdr/lib/vfs/vfs.h:18:5:
         18 |     Path() {}
            |     ^~~~
      • candidate expects 0 arguments, 2 provided
    • candidate 4: 'constexpr Path::Path(const Path&)'
      .obj/windows/lib/vfs/+vfs_hdr/lib/vfs/vfs.h:15:7:
         15 | class Path : public std::vector<std::string>
            |       ^~~~
      • candidate expects 1 argument, 2 provided
    • candidate 5: 'constexpr Path::Path(Path&&)'
      • candidate expects 1 argument, 2 provided
```
My compiler version is:
 gcc --version
gcc.exe (Rev2, Built by MSYS2 project) 16.1.0
Copyright (C) 2026 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by Sonic-Amiga** [comment]
Fix: https://github.com/davidgiven/fluxengine/pull/860

**Comment by Sonic-Amiga** [comment]
Fix merged. Thank you!
