### ISSUE TITLE
Again unable to build on macOS (M1, Ventura 13.4)

### ISSUE THREAD

**Issue by Yserra** [davidgiven/fluxengine#687]
Hi David,

All previous source code compiled without issue.
I just tried to "gmake" the latest source code (on June 11th, 2023) on my Mac M1/macOS Ventura 13.4 (my Homebrew tools/libraries were updated just before building). Here are the errors I get:
...
PROTOC .obj/arch/smaky6/smaky6.pb.h
arch/smaky6/smaky6.proto:3:1: warning: Import lib/common.proto is unused.
...
CXX arch/c64/encoder.cc
In file included from arch/c64/encoder.cc:1:
In file included from lib/globals.h:18:
In file included from /opt/homebrew/Cellar/fmt/10.0.0/include/fmt/format.h:49:
/opt/homebrew/Cellar/fmt/10.0.0/include/fmt/core.h:1690:3: error: static_assert failed due to requirement 'formattable' "Cannot format an argument. To make type T formattable provide a formatter<T> specialization: https://fmt.dev/latest/api.html#udt"
  static_assert(
  ^
/opt/homebrew/Cellar/fmt/10.0.0/include/fmt/core.h:1711:10: note: in instantiation of function template specialization 'fmt::detail::make_value<fmt::basic_format_context<fmt::appender, char>, std::__bit_reference<std::vector<bool>, true> &>' requested here
  return make_value<Context>(val);
             ^
/opt/homebrew/Cellar/fmt/10.0.0/include/fmt/core.h:1825:23: note: in instantiation of function template specialization 'fmt::detail::make_arg<true, fmt::basic_format_context<fmt::appender, char>, fmt::detail::type::custom_type, std::__bit_reference<std::vector<bool>, true> &, 0>' requested here
        data_{detail::make_arg<
                              ^
/opt/homebrew/Cellar/fmt/10.0.0/include/fmt/core.h:1844:10: note: in instantiation of function template specialization 'fmt::format_arg_store<fmt::basic_format_context<fmt::appender, char>, std::__bit_reference<std::vector<bool>, true>>::format_arg_store<std::__bit_reference<std::vector<bool>, true> &>' requested here
  return {FMT_FORWARD(args)...};
             ^
/opt/homebrew/Cellar/fmt/10.0.0/include/fmt/core.h:2817:28: note: in instantiation of function template specialization 'fmt::make_format_args<fmt::basic_format_context<fmt::appender, char>, std::__bit_reference<std::vector<bool>, true> &>' requested here
  return vformat(fmt, fmt::make_format_args(args...));
                                             ^
arch/c64/encoder.cc:64:32: note: in instantiation of function template specialization 'fmt::format<std::__bit_reference<std::vector<bool>, true>>' requested here
                stream << fmt::format("{:01b}", (buffer[pos + i]));
                                           ^
1 error generated.
gmake: *** [Makefile:271: .obj/arch/c64/encoder.o] Error 1
