### ISSUE TITLE
make does not work on ubuntu 20.04

### ISSUE THREAD

**Issue by wybren1971** [davidgiven/fluxengine#538]
I downloaded the latest sources and tried the make command and got the following output:
wybren@wybren-XPS-13-9380:~/gitwybren/fluxengine$ make
make: command: Command not found
src/gui/build.mk:35: wx-config missing, not building GUI
CXX src/fe-analysedriveresponse.cc
src/fe-analysedriveresponse.cc: In lambda function:
src/fe-analysedriveresponse.cc:167:33: error: ‘runtime’ is not a member of ‘fmt’
  167 |    x-8, y+5.0, fmt::format(fmt::runtime(format), v));
      |                                 ^~~~~~~
src/fe-analysedriveresponse.cc: In lambda function:
src/fe-analysedriveresponse.cc:184:30: error: ‘runtime’ is not a member of ‘fmt’
  184 |    x, y+18, fmt::format(fmt::runtime(format), v));
      |                              ^~~~~~~
At global scope:
cc1plus: warning: unrecognized command line option ‘-Wno-deprecated-enum-enum-conversion’
cc1plus: warning: unrecognized command line option ‘-Wno-deprecated-enum-float-conversion’
make: *** [Makefile:206: .obj/src/fe-analysedriveresponse.o] Error 1

What has changed? and how do i correct it on my system?

**Comment by davidgiven** [comment]
Ubuntu 20's C++ is very old. It doesn't seem to have `fmt::runtime`. Unfortunately, Ubuntu 22's C++ _requires_ `fmt::runtime'...

**Comment by davidgiven** [comment]
Workaround discovered.
