### ISSUE TITLE
Can't build on macOS 26.1 (25B78) (Tahoe)

### ISSUE THREAD

**Issue by hanshuebner** [davidgiven/fluxengine#836]
While trying to build fluxengine on macOS, I ran into issues like:
```
dep/imhex/lib/libimhex/source/helpers/crypto.cpp:11:10: fatal error: 'mbedtls/bignum.h' file not found
   11 | #include <mbedtls/bignum.h>
      |          ^~~~~~~~~~~~~~~~~~
1 error generated.
```
Apparently, this header files is part of mbedtls v3, but no longer exists in v4.  Homebrew installs v4 by default now and some other utilities link to it.  I've removed it from my machine as I don't need the other stuff, allowing me to `brew install mbedtls@3` and `brew link mbedtls@3`, but that is calling for trouble in the future.  If switching to v4 is not easy, maybe making the correct mbedtls version a submodule would be better?

**Comment by davidgiven** [comment]
Sorry for the delay --- yes, this is correct, you need to link mbedtls@3. The next version of ImHex is out RSN and should hopefully fix that. Once that's ready I'll upgrade my integration.
